// Generated by the protocol buffer gcless compiler.  DO NOT EDIT!
package com.x.protobuf;

import java.io.IOException;
public final class Bug3 {
private Bug3() {}
public static class B {
private String Id_string;
public static final int ID_STRING_FIELD_NUMBER = 1;
private boolean hasId_string;
public boolean hasId_string() {
return hasId_string;
}
public String getId_string() {
return Id_string;
}
public void setId_string(String Id_string) {
this.Id_string = Id_string;
this.hasId_string = true;
}
}
public static class BSerializer {
public static byte[] serialize(com.x.protobuf.Bug3.B message) {
try {
int totalSize = 0;
byte[] id_stringBuffer = null;
if (message.hasId_string()) {
id_stringBuffer = message.getId_string().getBytes("UTF-8");
totalSize += id_stringBuffer.length;
totalSize += ProtobufOutputStream.computeTagSize(1);
totalSize += ProtobufOutputStream.computeRawVarint32Size(id_stringBuffer.length);
}
final byte[] result = new byte[totalSize];
int position = 0;
if (message.hasId_string()) {
position = ProtobufOutputStream.writeString(1,id_stringBuffer, result, position);
}
ProtobufOutputStream.checkNoSpaceLeft(result, position);
return result;
} catch (IOException e) {
throw new RuntimeException("Serializing to a byte array threw an IOException (should never happen).", e);
}
}
public static void serialize(com.x.protobuf.Bug3.B message, java.io.OutputStream os) {
try {
if (message.hasId_string()) {
ProtobufOutputStream.writeString(1, message.getId_string(), os);
}
} catch (IOException e) {
throw new RuntimeException("Serializing to a byte array threw an IOException (should never happen).", e);
}
}
public static com.x.protobuf.Bug3.B parseFrom(byte[] data) throws java.io.IOException {
com.x.protobuf.Bug3.B message = new com.x.protobuf.Bug3.B();
CurrentCursor cursor = new CurrentCursor();
while(true) {
int tag = ProtobufInputStream.readTag(data,cursor);
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(tag, data, cursor);
 break;
case 1: 
message.setId_string(ProtobufInputStream.readString(data,cursor));
break;
}
}
}
public static com.x.protobuf.Bug3.B parseFrom(byte[] data, int offset, int length) throws java.io.IOException {
com.x.protobuf.Bug3.B message = new com.x.protobuf.Bug3.B();
CurrentCursor cursor = new CurrentCursor();
cursor.addToPosition(offset);
cursor.setProcessUpToPosition(offset + length);
while(true) {
int tag = ProtobufInputStream.readTag(data,cursor);
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(tag, data, cursor);
 break;
case 1: 
message.setId_string(ProtobufInputStream.readString(data,cursor));
break;
}
}
}
public static com.x.protobuf.Bug3.B parseFrom(java.io.InputStream is) throws java.io.IOException {
com.x.protobuf.Bug3.B message = new com.x.protobuf.Bug3.B();
CurrentCursor cursor = new CurrentCursor();
while(true) {
int tag = ProtobufInputStream.readTag(is,cursor);
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(tag, is, cursor);
 break;case 1: 
message.setId_string(ProtobufInputStream.readString(is,cursor));
break;
}
}
}
public static com.x.protobuf.Bug3.B parseFrom(java.io.InputStream is, int offset, int length) throws java.io.IOException {
com.x.protobuf.Bug3.B message = new com.x.protobuf.Bug3.B();
CurrentCursor cursor = new CurrentCursor();
cursor.addToPosition(offset);
cursor.setProcessUpToPosition(offset + length);
while(true) {
int tag = ProtobufInputStream.readTag(is,cursor);
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(tag, is, cursor);
 break;case 1: 
message.setId_string(ProtobufInputStream.readString(is,cursor));
break;
}
}
}
}
public static class A {
private com.x.protobuf.Bug3.B Entry;
public static final int ENTRY_FIELD_NUMBER = 32904;
private boolean hasEntry;
public boolean hasEntry() {
return hasEntry;
}
public com.x.protobuf.Bug3.B getEntry() {
return Entry;
}
public void setEntry(com.x.protobuf.Bug3.B Entry) {
this.Entry = Entry;
this.hasEntry = true;
}
}
public static class ASerializer {
public static byte[] serialize(com.x.protobuf.Bug3.A message) {
try {
int totalSize = 0;
byte[] entryBuffer = null;
if (message.hasEntry()) {
entryBuffer = com.x.protobuf.Bug3.BSerializer.serialize(message.getEntry());
totalSize += ProtobufOutputStream.computeTagSize(32904);
totalSize += ProtobufOutputStream.computeRawVarint32Size(entryBuffer.length);
totalSize += entryBuffer.length;
}
final byte[] result = new byte[totalSize];
int position = 0;
if (message.hasEntry()) {
position = ProtobufOutputStream.writeBytes(32904, entryBuffer, result, position);
}
ProtobufOutputStream.checkNoSpaceLeft(result, position);
return result;
} catch (IOException e) {
throw new RuntimeException("Serializing to a byte array threw an IOException (should never happen).", e);
}
}
public static void serialize(com.x.protobuf.Bug3.A message, java.io.OutputStream os) {
try {
if (message.hasEntry()) {
byte[] curMessageData = com.x.protobuf.Bug3.BSerializer.serialize(message.getEntry());
ProtobufOutputStream.writeMessageTag(32904, os);
ProtobufOutputStream.writeRawVarint32(curMessageData.length, os);
os.write(curMessageData);
}
} catch (IOException e) {
throw new RuntimeException("Serializing to a byte array threw an IOException (should never happen).", e);
}
}
public static com.x.protobuf.Bug3.A parseFrom(byte[] data) throws java.io.IOException {
com.x.protobuf.Bug3.A message = new com.x.protobuf.Bug3.A();
CurrentCursor cursor = new CurrentCursor();
while(true) {
int tag = ProtobufInputStream.readTag(data,cursor);
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(tag, data, cursor);
 break;
case 32904: 
int lengthEntry = ProtobufInputStream.readRawVarint32(data,cursor);
message.setEntry(com.x.protobuf.Bug3.BSerializer.parseFrom(data, cursor.getCurrentPosition(), lengthEntry));
cursor.addToPosition(lengthEntry);
break;
}
}
}
public static com.x.protobuf.Bug3.A parseFrom(byte[] data, int offset, int length) throws java.io.IOException {
com.x.protobuf.Bug3.A message = new com.x.protobuf.Bug3.A();
CurrentCursor cursor = new CurrentCursor();
cursor.addToPosition(offset);
cursor.setProcessUpToPosition(offset + length);
while(true) {
int tag = ProtobufInputStream.readTag(data,cursor);
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(tag, data, cursor);
 break;
case 32904: 
int lengthEntry = ProtobufInputStream.readRawVarint32(data,cursor);
message.setEntry(com.x.protobuf.Bug3.BSerializer.parseFrom(data, cursor.getCurrentPosition(), lengthEntry));
cursor.addToPosition(lengthEntry);
break;
}
}
}
public static com.x.protobuf.Bug3.A parseFrom(java.io.InputStream is) throws java.io.IOException {
com.x.protobuf.Bug3.A message = new com.x.protobuf.Bug3.A();
CurrentCursor cursor = new CurrentCursor();
while(true) {
int tag = ProtobufInputStream.readTag(is,cursor);
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(tag, is, cursor);
 break;case 32904: 
int lengthEntry = ProtobufInputStream.readRawVarint32(is,cursor);
message.setEntry(com.x.protobuf.Bug3.BSerializer.parseFrom(is, cursor.getCurrentPosition(), lengthEntry));
break;
}
}
}
public static com.x.protobuf.Bug3.A parseFrom(java.io.InputStream is, int offset, int length) throws java.io.IOException {
com.x.protobuf.Bug3.A message = new com.x.protobuf.Bug3.A();
CurrentCursor cursor = new CurrentCursor();
cursor.addToPosition(offset);
cursor.setProcessUpToPosition(offset + length);
while(true) {
int tag = ProtobufInputStream.readTag(is,cursor);
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(tag, is, cursor);
 break;case 32904: 
int lengthEntry = ProtobufInputStream.readRawVarint32(is,cursor);
message.setEntry(com.x.protobuf.Bug3.BSerializer.parseFrom(is, cursor.getCurrentPosition(), lengthEntry));
break;
}
}
}
}
}

