package com.google.code.proto.gcless;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MemlessGenerator {

	private static final String HEADER = "// Generated by the protocol buffer gcless compiler.  DO NOT EDIT!\n";

	public static void main(String[] args) {
		if (args.length < 2) {
			System.out.println("invalid usage. Expected: <output-path> <proto-files>");
			return;
		}

		File output = new File(args[0]);
		if (!output.exists()) {
			System.out.println("<output-path> doesnt exist");
			return;
		}
		if (!output.isDirectory()) {
			System.out.println("<output-path> is not a directory");
			return;
		}

		for (int i = 1; i < args.length; i++) {
			try {
				process(output, args[i]);
			} catch (Exception e) {
				System.out.println("unable to process: " + args[i]);
				e.printStackTrace();
			}
		}
	}

	private static void process(File output, String filename) throws Exception {
		MemlessParser parser = new MemlessParser();
		parser.process(filename);
		String packageName = parser.getPackageName();
		if (packageName != null) {
			output = createPackage(output, packageName);
		}

		BufferedWriter w = null;
		if (parser.getOuterClassName() != null) {
			w = new BufferedWriter(new FileWriter(new File(output, parser.getOuterClassName() + ".java")));
			w.append(HEADER);
			appendPackage(w, parser.getPackageName());
			appendImport(w, "java.io.IOException");
			w.append("public final class ");
			w.append(parser.getOuterClassName());
			w.append(" {\nprivate ");
			w.append(parser.getOuterClassName());
			w.append("() {}\n");
		}

		for (ProtobufEnum curEnum : parser.getEnums()) {
			String curEnumData = generateEnum(curEnum);
			if (parser.getOuterClassName() != null) {
				w.append(curEnumData);
			} else {
				BufferedWriter enumWriter = new BufferedWriter(new FileWriter(new File(output, curEnum.getName() + ".java")));
				appendPackage(enumWriter, parser.getPackageName());
				enumWriter.append(curEnumData);
				enumWriter.flush();
				enumWriter.close();
			}
		}

		String interfaceBased = System.getProperty("interface.based");
		boolean isInterfaceBased = false;
		if (interfaceBased != null && interfaceBased.equals("true")) {
			isInterfaceBased = true;
		}

		for (ProtobufMessage curMessage : parser.getMessages()) {
			String curMessageData = generateMessage(curMessage, parser.getOuterClassName(), isInterfaceBased);
			String serializerData = generateSerializer(curMessage, parser.getOuterClassName(), isInterfaceBased);

			if (parser.getOuterClassName() != null) {
				w.append(curMessageData);
				w.append(serializerData);
			} else {
				BufferedWriter messageWriter = new BufferedWriter(new FileWriter(new File(output, curMessage.getName() + ".java")));
				appendPackage(messageWriter, parser.getPackageName());
				messageWriter.append(curMessageData);
				messageWriter.flush();
				messageWriter.close();
				messageWriter = new BufferedWriter(new FileWriter(new File(output, curMessage.getName() + "Serializer" + ".java")));
				appendPackage(messageWriter, parser.getPackageName());
				if (!curMessage.getFields().isEmpty()) {
					appendImport(messageWriter, "java.io.IOException");
				}
				messageWriter.append(serializerData);
				messageWriter.flush();
				messageWriter.close();
			}
		}

		if (parser.getOuterClassName() != null) {
			w.append("}\n\n");
			w.flush();
			w.close();
		}

		if (isInterfaceBased) {
			String generateDefaultImpl = System.getProperty("generate.default");
			if (generateDefaultImpl != null && generateDefaultImpl.equals("true")) {
				for (ProtobufMessage curMessage : parser.getMessages()) {
					generateDefaultMessageImpl(curMessage, output, parser.getPackageName());
				}
			}
		}
		copy("ProtobufOutputStream.java", output);
		copy("ProtobufInputStream.java", output);
		copy("CurrentCursor.java", output);
		copy("MessageFactory.java", output);
	}

	private static void copy(String classpathFileName, File output) throws IOException {
		InputStream protobufOutputStream = MemlessGenerator.class.getResourceAsStream(classpathFileName);
		if (protobufOutputStream == null) {
			throw new IOException("Cannot find " + classpathFileName + " in classpath");
		}
		FileOutputStream fos = null;
		try {
			fos = new FileOutputStream(new File(output, classpathFileName));
			copy(protobufOutputStream, fos, 2048);
		} finally {
			if (protobufOutputStream != null) {
				protobufOutputStream.close();
			}
			if (fos != null) {
				fos.close();
			}
		}
	}

	private static void copy(InputStream input, OutputStream output, int bufferSize) throws IOException {
		byte[] buf = new byte[bufferSize];
		int bytesRead = input.read(buf);
		while (bytesRead != -1) {
			output.write(buf, 0, bytesRead);
			bytesRead = input.read(buf);
		}
		output.flush();
	}

	private static String generateSerializer(ProtobufMessage curMessage, String outerClassName, boolean interfaceBased) {
		StringBuilder result = new StringBuilder();
		String fullMessageType = curMessage.getFullyClarifiedName();
		if (outerClassName == null) {
			result.append("public final class ");
		} else {
			result.append("public static class ");
		}
		result.append(curMessage.getName());
		result.append("Serializer {\n");
		createSerializeToBytes(curMessage, outerClassName, result, fullMessageType);
		createSerializeToStream(curMessage, result, fullMessageType);
		createParseFromBytes(curMessage, interfaceBased, result, fullMessageType);
		createParseFromBytesWithLimit(curMessage, interfaceBased, result, fullMessageType);
		createParseFromStream(curMessage, interfaceBased, result, fullMessageType);
		createParseFromStreamWithLength(curMessage, interfaceBased, result, fullMessageType);
		if (hasRequired(curMessage)) {
			createAssertInitialized(curMessage, result, fullMessageType);
		}
		result.append("}\n");
		return result.toString();
	}

	private static void createSerializeToBytes(ProtobufMessage curMessage, String outerClassName, StringBuilder result, String fullMessageType) {
		result.append("public static byte[] serialize(" + fullMessageType + " message) {\n");
		if (curMessage.getFields().isEmpty()) {
			result.append("return new byte[0];\n");
		} else {
			result.append("try {\n");
			if (hasRequired(curMessage)) {
				result.append("assertInitialized(message);\n");
			}
			result.append("int totalSize = 0;\n");
			for (ProtobufField curField : curMessage.getFields()) {
				if (curField.isEnumType()) {
					if (curField.getNature().equals("repeated")) {
						result.append("byte[] " + curField.getName() + "Buffer = null;\n");
						result.append("if (message.has" + curField.getBeanName() + "()) {\n");
						result.append("java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();\n");
						result.append("for( int i=0;i<message.get" + curField.getBeanName() + "().size();i++) {\n");
						result.append("ProtobufOutputStream.writeEnum(" + curField.getTag() + ", message.get" + curField.getBeanName() + "().get(i).getValue(), baos);\n");
						result.append("}\n");
						result.append(curField.getName() + "Buffer = baos.toByteArray();\n");
						result.append("totalSize += " + curField.getName() + "Buffer.length;\n");
					} else {
						result.append("if (message.has" + curField.getBeanName() + "()) {\n");
						result.append("totalSize += ProtobufOutputStream.computeEnumSize(" + curField.getTag() + ", message.get" + curField.getBeanName() + "().getValue());\n");
					}
					result.append("}\n");
					continue;
				}
				if (curField.isComplexType()) {
					result.append("byte[] " + curField.getName() + "Buffer = null;\n");
					result.append("if (message.has" + curField.getBeanName() + "()) {\n");
					if (curField.getNature().equals("repeated")) {
						result.append("java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();\n");
						result.append("for( int i=0;i<message.get" + curField.getBeanName() + "().size();i++) {\n");
						result.append("byte[] curMessageData = " + curField.getFullyClarifiedJavaType() + "Serializer.serialize(message.get" + curField.getBeanName() + "().get(i));\n");
						result.append("ProtobufOutputStream.writeMessageTag(" + curField.getTag() + ", baos);\n");
						result.append("ProtobufOutputStream.writeRawVarint32(curMessageData.length, baos);\n");
						result.append("baos.write(curMessageData);\n");
						result.append("}\n");
						result.append(curField.getName() + "Buffer = baos.toByteArray();\n");
					} else {
						result.append(curField.getName() + "Buffer = " + curField.getFullyClarifiedJavaType() + "Serializer.serialize(message.get" + curField.getBeanName() + "());\n");
						result.append("totalSize += ProtobufOutputStream.computeTagSize(" + curField.getTag() + ");\n");
						result.append("totalSize += ProtobufOutputStream.computeRawVarint32Size(" + curField.getName() + "Buffer.length);\n");
					}
					result.append("totalSize += " + curField.getName() + "Buffer.length;\n");
					result.append("}\n");
					continue;
				}
				if (curField.getType().equals("string")) {
					result.append("byte[] " + curField.getName() + "Buffer = null;\n");
					result.append("if (message.has" + curField.getBeanName() + "()) {\n");
					if (curField.getNature().equals("repeated")) {
						result.append("java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();\n");
						result.append("for( int i=0;i<message.get" + curField.getBeanName() + "().size();i++) {\n");
						result.append("ProtobufOutputStream.writeString(" + curField.getTag() + ", message.get" + curField.getBeanName() + "().get(i), baos);\n");
						result.append("}\n");
						result.append(curField.getName() + "Buffer = baos.toByteArray();\n");
						result.append("totalSize += " + curField.getName() + "Buffer.length;\n");
					} else {
						result.append(curField.getName() + "Buffer = message.get" + curField.getBeanName() + "().getBytes(\"UTF-8\");\n");
						result.append("totalSize += " + curField.getName() + "Buffer.length;\n");
						result.append("totalSize += ProtobufOutputStream.computeTagSize(" + curField.getTag() + ");\n");
						result.append("totalSize += ProtobufOutputStream.computeRawVarint32Size(" + curField.getName() + "Buffer.length);\n");
					}
					result.append("}\n");
					continue;
				}

				if (curField.getNature().equals("repeated")) {
					result.append("if (message.has" + curField.getBeanName() + "()) {\n");
					if (curField.getType().equals("bytes")) {
						result.append("totalSize += ProtobufOutputStream.computeBytesSize(" + curField.getTag() + ", message.get" + curField.getBeanName() + "());\n");
					} else {
						result.append("for(int i=0;i<message.get" + curField.getBeanName() + "().size();i++) {\n");
						result.append("totalSize += ProtobufOutputStream.compute" + curField.getStreamBeanType() + "Size(" + curField.getTag() + ", message.get" + curField.getBeanName() + "().get(i));\n");
						result.append("}\n");
					}
					result.append("}\n");
				} else {
					result.append("if (message.has" + curField.getBeanName() + "()) {\n");
					result.append("totalSize += ");
					if (curField.getType().equals("bytes")) {
						result.append("message.get" + curField.getBeanName() + "().length;\n");
						result.append("totalSize += ProtobufOutputStream.computeTagSize(" + curField.getTag() + ");\n");
						result.append("totalSize += ProtobufOutputStream.computeRawVarint32Size(message.get" + curField.getBeanName() + "().length);\n");
					} else {
						result.append("ProtobufOutputStream.compute" + curField.getStreamBeanType() + "Size(" + curField.getTag() + ", message.get" + curField.getBeanName() + "());\n");
					}
					result.append("}\n");
				}
			}
			result.append("final byte[] result = new byte[totalSize];\nint position = 0;\n");
			for (ProtobufField curField : curMessage.getFields()) {
				result.append("if (message.has" + curField.getBeanName() + "()) {\n");
				if (curField.getType().equals("string")) {
					if (curField.getNature().equals("repeated")) {
						result.append("position = ProtobufOutputStream.writeRawBytes(" + curField.getName() + "Buffer, result, position);\n");
					} else {
						result.append("position = ProtobufOutputStream.writeString(" + curField.getTag() + "," + curField.getName() + "Buffer, result, position);\n");
					}
					result.append("}\n");
					continue;
				}

				if (curField.isEnumType()) {
					if (curField.getNature().equals("repeated")) {
						result.append("position = ProtobufOutputStream.writeRawBytes(" + curField.getName() + "Buffer, result, position);\n");
					} else {
						result.append("position = ProtobufOutputStream.writeEnum(" + curField.getTag() + ", message.get" + curField.getBeanName() + "().getValue(), result, position);\n");
					}
					result.append("}\n");
					continue;
				}

				if (curField.getNature().equals("repeated")) {
					if (curField.isComplexType()) {
						result.append("position = ProtobufOutputStream.writeRawBytes(" + curField.getName() + "Buffer, result, position);\n");
					} else {
						result.append("position = ProtobufOutputStream.writeRepeated" + curField.getStreamBeanType() + "(" + curField.getTag() + ", message.get" + curField.getBeanName() + "(), result, position);\n");
					}
				} else {
					result.append("position = ProtobufOutputStream.write");
					if (!curField.isComplexType()) {
						result.append(curField.getStreamBeanType());
						result.append("(");
						result.append(curField.getTag());
						result.append(", message.get");
						result.append(curField.getBeanName());
						result.append("(), result, position);\n");
					} else {
						result.append("Bytes(" + curField.getTag() + ", " + curField.getName() + "Buffer, result, position);\n");
					}
				}
				result.append("}\n");
			}
			result.append("ProtobufOutputStream.checkNoSpaceLeft(result, position);\n");
			result.append("return result;\n");
			result.append("} catch (IOException e) {\n");
			result.append("throw new RuntimeException(\"Serializing to a byte array threw an IOException (should never happen).\", e);\n");
			result.append("}\n");
		}
		result.append("}\n");
	}

	private static void createAssertInitialized(ProtobufMessage curMessage, StringBuilder result, String fullMessageType) {
		result.append("private static void assertInitialized(");
		result.append(fullMessageType);
		result.append(" message) {\n");
		for (ProtobufField curField : curMessage.getFields()) {
			if (curField.getNature().equals("required")) {
				result.append("if( !message.has" + curField.getBeanName() + "()) {\n");
				result.append("throw new IllegalArgumentException(\"Required field not initialized: ");
				result.append(curField.getName());
				result.append("\");\n}\n");
			}
		}
		result.append("}\n");
	}

	private static void createSerializeToStream(ProtobufMessage curMessage, StringBuilder result, String fullMessageType) {
		result.append("public static void serialize(" + fullMessageType + " message, java.io.OutputStream os) {\n");
		if (curMessage.getFields().isEmpty()) {
			result.append("return; \n");
		} else {
			result.append("try {\n");
			if (hasRequired(curMessage)) {
				result.append("assertInitialized(message);\n");
			}
			for (ProtobufField curField : curMessage.getFields()) {
				result.append("if (message.has" + curField.getBeanName() + "()) {\n");
				if (curField.getType().equals("string")) {
					if (curField.getNature().equals("repeated")) {
						result.append("for( int i=0;i<message.get" + curField.getBeanName() + "().size();i++) {\n");
						result.append("ProtobufOutputStream.writeString(" + curField.getTag() + ", message.get" + curField.getBeanName() + "().get(i), os);\n");
						result.append("}\n");
					} else {
						result.append("ProtobufOutputStream.writeString(" + curField.getTag() + ", message.get" + curField.getBeanName() + "(), os);\n");
					}
				} else if (curField.isEnumType()) {
					if (curField.getNature().equals("repeated")) {
						result.append("for( int i=0;i<message.get" + curField.getBeanName() + "().size();i++) {\n");
						result.append("ProtobufOutputStream.writeEnum(" + curField.getTag() + ", message.get" + curField.getBeanName() + "().get(i).getValue(), os);\n");
						result.append("}\n");
					} else {
						result.append("ProtobufOutputStream.writeEnum(" + curField.getTag() + ", message.get" + curField.getBeanName() + "().getValue(), os);\n");
					}
				} else if (curField.isComplexType()) {
					if (curField.getNature().equals("repeated")) {
						result.append("for( int i=0;i<message.get" + curField.getBeanName() + "().size();i++) {\n");
						result.append("byte[] curMessageData = " + curField.getFullyClarifiedJavaType() + "Serializer.serialize(message.get" + curField.getBeanName() + "().get(i));\n");
						result.append("ProtobufOutputStream.writeMessageTag(" + curField.getTag() + ", os);\n");
						result.append("ProtobufOutputStream.writeRawVarint32(curMessageData.length, os);\n");
						result.append("os.write(curMessageData);\n");
						result.append("}\n");
					} else {
						result.append("byte[] curMessageData = " + curField.getFullyClarifiedJavaType() + "Serializer.serialize(message.get" + curField.getBeanName() + "());\n");
						result.append("ProtobufOutputStream.writeMessageTag(" + curField.getTag() + ", os);\n");
						result.append("ProtobufOutputStream.writeRawVarint32(curMessageData.length, os);\n");
						result.append("os.write(curMessageData);\n");
					}
				} else if (curField.getType().equals("bytes")) {
					result.append("ProtobufOutputStream.writeBytes(");
					result.append(curField.getTag());
					result.append(", message.get");
					result.append(curField.getBeanName());
					result.append("(), os);\n");
				} else {
					if (curField.getNature().equals("repeated")) {
						result.append("for( int i=0;i<message.get" + curField.getBeanName() + "().size();i++) {\n");
						result.append("ProtobufOutputStream.write");
						result.append(curField.getStreamBeanType());
						result.append("(");
						result.append(curField.getTag());
						result.append(", message.get");
						result.append(curField.getBeanName());
						result.append("().get(i), os);\n");
						result.append("}\n");
					} else {
						result.append("ProtobufOutputStream.write");
						result.append(curField.getStreamBeanType());
						result.append("(");
						result.append(curField.getTag());
						result.append(", message.get");
						result.append(curField.getBeanName());
						result.append("(), os);\n");
					}
				}
				result.append("}\n");
			}
			result.append("} catch (IOException e) {\n");
			result.append("throw new RuntimeException(\"Serializing to a byte array threw an IOException (should never happen).\", e);\n");
			result.append("}\n");
		}
		result.append("}\n");
	}

	private static void createParseFromBytesWithLimit(ProtobufMessage curMessage, boolean interfaceBased, StringBuilder result, String fullMessageType) {
		if (interfaceBased) {
			result.append("public static " + fullMessageType + " parseFrom(MessageFactory factory, byte[] data, int offset, int length) throws java.io.IOException {\n");
			result.append(fullMessageType + " message = (" + curMessage.getFullyClarifiedName() + ")factory.create(\"" + curMessage.getFullyClarifiedName() + "\");\n");
			result.append("if( message == null || !(message instanceof " + curMessage.getFullyClarifiedName() + ")) { \n");
			result.append("throw new IOException(\"Factory create invalid message for type: " + curMessage.getFullyClarifiedName() + "\");\n");
			result.append("}\n");
		} else {
			result.append("public static " + fullMessageType + " parseFrom(byte[] data, int offset, int length) throws java.io.IOException {\n");
			result.append(fullMessageType + " message = new " + fullMessageType + "();\n");
		}
		result.append("CurrentCursor cursor = new CurrentCursor();\n");
		result.append("cursor.addToPosition(offset);\n");
		result.append("cursor.setProcessUpToPosition(offset + length);\n");
		createParseFromBytesBody(curMessage, result, interfaceBased);
		result.append("}\n");
	}

	private static void createParseFromBytes(ProtobufMessage curMessage, boolean interfaceBased, StringBuilder result, String fullMessageType) {
		if (interfaceBased) {
			result.append("public static " + fullMessageType + " parseFrom(MessageFactory factory, byte[] data) throws java.io.IOException {\n");
			result.append(fullMessageType + " message = (" + curMessage.getFullyClarifiedName() + ")factory.create(\"" + curMessage.getFullyClarifiedName() + "\");\n");
			result.append("if( message == null || !(message instanceof " + curMessage.getFullyClarifiedName() + ")) { \n");
			result.append("throw new IOException(\"Factory create invalid message for type: " + curMessage.getFullyClarifiedName() + "\");\n");
			result.append("}\n");
		} else {
			result.append("public static " + fullMessageType + " parseFrom(byte[] data) throws java.io.IOException {\n");
			result.append(fullMessageType + " message = new " + fullMessageType + "();\n");
		}
		result.append("CurrentCursor cursor = new CurrentCursor();\n");
		createParseFromBytesBody(curMessage, result, interfaceBased);
		result.append("}\n");
	}

	private static void createParseFromBytesBody(ProtobufMessage curMessage, StringBuilder result, boolean interfaceBased) {
		String factory = "";
		if (interfaceBased) {
			factory = "factory, ";
		}
		result.append("while(true) {\n");
		result.append("int tag = ProtobufInputStream.readTag(data,cursor);\n");
		result.append("switch(tag) {\n");
		result.append("case 0: \n");
		result.append("return message;\n ");
		result.append("default: \n ProtobufInputStream.skipUnknown(tag, data, cursor);\n break;\n");
		for (ProtobufField curField : curMessage.getFields()) {
			result.append("case " + curField.getTag() + ": \n");
			if (curField.isEnumType()) {
				if (curField.getNature().equals("repeated")) {
					result.append("if( message.get" + curField.getBeanName() + "() == null || message.get" + curField.getBeanName() + "().isEmpty()) {\n");
					result.append("message.set" + curField.getBeanName() + "(new java.util.ArrayList<" + curField.getFullyClarifiedJavaType() + ">());\n");
					result.append("}\n");
					result.append("message.get" + curField.getBeanName() + "().add(" + curField.getFullyClarifiedJavaType() + ".valueOf(ProtobufInputStream.readEnum(data,cursor)));\n");
				} else {
					result.append("message.set" + curField.getBeanName() + "(" + curField.getFullyClarifiedJavaType() + ".valueOf(ProtobufInputStream.readEnum(data,cursor)));\n");
				}
			} else if (curField.isComplexType()) {
				if (curField.getNature().equals("repeated")) {
					result.append("if( message.get" + curField.getBeanName() + "() == null || message.get" + curField.getBeanName() + "().isEmpty()) {\n");
					result.append("message.set" + curField.getBeanName() + "(new java.util.ArrayList<" + curField.getFullyClarifiedJavaType() + ">());\n");
					result.append("}\n");
					result.append("int length" + curField.getBeanName() + " = ProtobufInputStream.readRawVarint32(data,cursor);\n");
					result.append("message.get" + curField.getBeanName() + "().add(" + curField.getFullyClarifiedJavaType() + "Serializer.parseFrom(" + factory + "data, cursor.getCurrentPosition(), length" + curField.getBeanName() + "));\n");
					result.append("cursor.addToPosition(length" + curField.getBeanName() + ");\n");
				} else {
					result.append("int length" + curField.getBeanName() + " = ProtobufInputStream.readRawVarint32(data,cursor);\n");
					result.append("message.set" + curField.getBeanName() + "(" + curField.getFullyClarifiedJavaType() + "Serializer.parseFrom(" + factory + "data, cursor.getCurrentPosition(), length" + curField.getBeanName() + "));\n");
					result.append("cursor.addToPosition(length" + curField.getBeanName() + ");\n");
				}
			} else if (curField.getType().equals("bytes")) {
				result.append("message.set" + curField.getBeanName() + "(ProtobufInputStream.readBytes(data,cursor));\n");
			} else {
				if (curField.getNature().equals("repeated")) {
					result.append("if( message.get" + curField.getBeanName() + "() == null || message.get" + curField.getBeanName() + "().isEmpty()) {\n");
					result.append("message.set" + curField.getBeanName() + "(new java.util.ArrayList<" + curField.getFullyClarifiedJavaType() + ">());\n");
					result.append("}\n");
					result.append("message.get" + curField.getBeanName() + "().add(ProtobufInputStream.read" + curField.getStreamBeanType() + "(data,cursor));\n");
				} else {
					result.append("message.set" + curField.getBeanName() + "(ProtobufInputStream.read" + curField.getStreamBeanType() + "(data,cursor));\n");
				}
			}
			result.append("break;\n");
		}
		result.append("}\n");
		result.append("}\n");
	}

	private static void createParseFromStreamWithLength(ProtobufMessage curMessage, boolean interfaceBased, StringBuilder result, String fullMessageType) {
		//streamed read
		if (interfaceBased) {
			result.append("public static " + fullMessageType + " parseFrom(MessageFactory factory, java.io.InputStream is, int offset, int length) throws java.io.IOException {\n");
			result.append(fullMessageType + " message = (" + curMessage.getFullyClarifiedName() + ")factory.create(\"" + curMessage.getFullyClarifiedName() + "\");\n");
			result.append("if( message == null || !(message instanceof " + curMessage.getFullyClarifiedName() + ")) { \n");
			result.append("throw new IOException(\"Factory create invalid message for type: " + curMessage.getFullyClarifiedName() + "\");\n");
			result.append("}\n");
		} else {
			result.append("public static " + fullMessageType + " parseFrom(java.io.InputStream is, int offset, int length) throws java.io.IOException {\n");
			result.append(fullMessageType + " message = new " + fullMessageType + "();\n");
		}
		result.append("CurrentCursor cursor = new CurrentCursor();\n");
		result.append("cursor.addToPosition(offset);\n");
		result.append("cursor.setProcessUpToPosition(offset + length);\n");
		createParseFromStreamBody(curMessage, result, interfaceBased);
		result.append("}\n");
	}

	private static void createParseFromStream(ProtobufMessage curMessage, boolean interfaceBased, StringBuilder result, String fullMessageType) {
		//streamed read
		if (interfaceBased) {
			result.append("/** Beware! All subsequent messages in stream will be consumed until end of stream (default protobuf behaivour).\n  **/");
			result.append("public static " + fullMessageType + " parseFrom(MessageFactory factory, java.io.InputStream is) throws java.io.IOException {\n");
			result.append(fullMessageType + " message = (" + curMessage.getFullyClarifiedName() + ")factory.create(\"" + curMessage.getFullyClarifiedName() + "\");\n");
			result.append("if( message == null || !(message instanceof " + curMessage.getFullyClarifiedName() + ")) { \n");
			result.append("throw new IOException(\"Factory create invalid message for type: " + curMessage.getFullyClarifiedName() + "\");\n");
			result.append("}\n");
		} else {
			result.append("public static " + fullMessageType + " parseFrom(java.io.InputStream is) throws java.io.IOException {\n");
			result.append(fullMessageType + " message = new " + fullMessageType + "();\n");
		}
		result.append("CurrentCursor cursor = new CurrentCursor();\n");
		createParseFromStreamBody(curMessage, result, interfaceBased);
		result.append("}\n");
	}

	private static void createParseFromStreamBody(ProtobufMessage curMessage, StringBuilder result, boolean interfaceBased) {
		result.append("while(true) {\n");
		result.append("int tag = ProtobufInputStream.readTag(is,cursor);\n");
		result.append("switch(tag) {\n");
		result.append("case 0: \n");
		result.append("return message;\n ");
		result.append("default: \n ProtobufInputStream.skipUnknown(tag, is, cursor);\n break;");
		String factory = "";
		if (interfaceBased) {
			factory = "factory, ";
		}
		for (ProtobufField curField : curMessage.getFields()) {
			result.append("case " + curField.getTag() + ": \n");
			if (curField.isEnumType()) {
				if (curField.getNature().equals("repeated")) {
					result.append("if( message.get" + curField.getBeanName() + "() == null || message.get" + curField.getBeanName() + "().isEmpty()) {\n");
					result.append("message.set" + curField.getBeanName() + "(new java.util.ArrayList<" + curField.getFullyClarifiedJavaType() + ">());\n");
					result.append("}\n");
					result.append("message.get" + curField.getBeanName() + "().add(" + curField.getFullyClarifiedJavaType() + ".valueOf(ProtobufInputStream.readEnum(is,cursor)));\n");
				} else {
					result.append("message.set" + curField.getBeanName() + "(" + curField.getFullyClarifiedJavaType() + ".valueOf(ProtobufInputStream.readEnum(is,cursor)));\n");
				}
			} else if (curField.isComplexType()) {
				if (curField.getNature().equals("repeated")) {
					result.append("if( message.get" + curField.getBeanName() + "() == null || message.get" + curField.getBeanName() + "().isEmpty()) {\n");
					result.append("message.set" + curField.getBeanName() + "(new java.util.ArrayList<" + curField.getFullyClarifiedJavaType() + ">());\n");
					result.append("}\n");
					result.append("int length" + curField.getBeanName() + " = ProtobufInputStream.readRawVarint32(is,cursor);\n");
					result.append("message.get" + curField.getBeanName() + "().add(" + curField.getFullyClarifiedJavaType() + "Serializer.parseFrom(" + factory + "is, cursor.getCurrentPosition(), length" + curField.getBeanName() + "));\n");
				} else {
					result.append("int length" + curField.getBeanName() + " = ProtobufInputStream.readRawVarint32(is,cursor);\n");
					result.append("message.set" + curField.getBeanName() + "(" + curField.getFullyClarifiedJavaType() + "Serializer.parseFrom(" + factory + "is, cursor.getCurrentPosition(), length" + curField.getBeanName() + "));\n");
				}
			} else if (curField.getType().equals("bytes")) {
				result.append("message.set" + curField.getBeanName() + "(ProtobufInputStream.readBytes(is,cursor));\n");
			} else {
				if (curField.getNature().equals("repeated")) {
					result.append("if( message.get" + curField.getBeanName() + "() == null || message.get" + curField.getBeanName() + "().isEmpty()) {\n");
					result.append("message.set" + curField.getBeanName() + "(new java.util.ArrayList<" + curField.getFullyClarifiedJavaType() + ">());\n");
					result.append("}\n");
					result.append("message.get" + curField.getBeanName() + "().add(ProtobufInputStream.read" + curField.getStreamBeanType() + "(is,cursor));\n");
				} else {
					result.append("message.set" + curField.getBeanName() + "(ProtobufInputStream.read" + curField.getStreamBeanType() + "(is,cursor));\n");
				}
			}
			result.append("break;\n");
		}
		result.append("}\n");
		result.append("}\n");
	}

	private static void generateDefaultMessageImpl(ProtobufMessage curMessage, File output, String packageName) throws Exception {
		StringBuilder result = new StringBuilder();
		result.append("public class " + curMessage.getName() + "Impl implements " + curMessage.getFullyClarifiedName() + " {\n");
		for (ProtobufField curField : curMessage.getFields()) {
			String javaType = constructType(curField, curMessage);
			result.append("private " + javaType + " " + curField.getBeanName() + ";\n");
			result.append("private boolean has" + curField.getBeanName() + ";\n");
			result.append("public boolean has" + curField.getBeanName() + "() {\n");
			result.append("return has" + curField.getBeanName() + ";\n");
			result.append("}\n");
			result.append("public " + javaType + " get" + curField.getBeanName() + "() {\n");
			result.append("return " + curField.getBeanName() + ";\n");
			result.append("}\n");
			result.append("public void set" + curField.getBeanName() + "(" + javaType + " " + curField.getBeanName() + ") {\n");
			result.append("this." + curField.getBeanName() + " = " + curField.getBeanName() + ";\n");
			result.append("this.has" + curField.getBeanName() + " = true;\n");
			result.append("}\n");
		}
		result.append("}\n");

		//TODO check outer class
		File outputFile = new File(output, curMessage.getName() + "Impl.java");
		BufferedWriter messageWriter = new BufferedWriter(new FileWriter(outputFile));
		appendPackage(messageWriter, packageName);
		messageWriter.append(result.toString());
		messageWriter.flush();
		messageWriter.close();

		if (curMessage.getNestedMessages() != null) {
			for (ProtobufMessage message : curMessage.getNestedMessages()) {
				generateDefaultMessageImpl(message, output, packageName);
			}
		}

	}

	private static String generateMessage(ProtobufMessage curMessage, String outerClassName, boolean interfaceBased) {
		StringBuilder result = new StringBuilder();
		if (interfaceBased) {
			result.append("public interface ");
			result.append(curMessage.getName());
			result.append(" {\n");
			for (ProtobufField curField : curMessage.getFields()) {
				if (curField.isDeprecated()) {
					result.append("@Deprecated\n");
				}
				result.append("boolean has");
				result.append(curField.getBeanName());
				result.append("();\n");
				String javaType = constructType(curField, curMessage);
				if (curField.isDeprecated()) {
					result.append("@Deprecated\n");
				}
				result.append(javaType);
				result.append(" get");
				result.append(curField.getBeanName());
				result.append("();\n");
				if (curField.isDeprecated()) {
					result.append("@Deprecated\n");
				}
				result.append("void set");
				result.append(curField.getBeanName());
				result.append("(");
				result.append(javaType);
				result.append(" ");
				result.append(curField.getName());
				result.append(");\n");
			}
		} else {
			result.append("public class " + curMessage.getName() + " {\n");
			for (ProtobufField curField : curMessage.getFields()) {
				String javaType = constructType(curField, curMessage);
				result.append("private " + javaType + " " + curField.getBeanName() + ";\n");
				result.append("private boolean has" + curField.getBeanName() + ";\n");
				result.append("public boolean has" + curField.getBeanName() + "() {\n");
				result.append("return has" + curField.getBeanName() + ";\n");
				result.append("}\n");
				result.append("public " + javaType + " get" + curField.getBeanName() + "() {\n");
				result.append("return " + curField.getBeanName() + ";\n");
				result.append("}\n");
				result.append("public void set" + curField.getBeanName() + "(" + javaType + " " + curField.getBeanName() + ") {\n");
				result.append("this." + curField.getBeanName() + " = " + curField.getBeanName() + ";\n");
				result.append("this.has" + curField.getBeanName() + " = true;\n");
				result.append("}\n");
			}
		}

		for (ProtobufMessage innerMessage : curMessage.getNestedMessages()) {
			result.append(generateMessage(innerMessage, outerClassName, interfaceBased));
			String serializerData = generateSerializer(innerMessage, outerClassName, interfaceBased);
			result.append(serializerData);
		}
		for (ProtobufEnum curEnum : curMessage.getEnums()) {
			result.append(generateEnum(curEnum));
		}
		result.append("}\n");
		return result.toString();
	}

	private static String generateEnum(ProtobufEnum pEnum) {
		StringBuilder result = new StringBuilder();
		result.append("public enum ");
		result.append(pEnum.getName());
		result.append(" {\n");
		Map<Long, EnumValue> added = new HashMap<Long, EnumValue>();
		List<EnumValue> duplicate = new ArrayList<EnumValue>();
		for (EnumValue curValue : pEnum.getValues()) {
			if (added.containsKey(curValue.getId())) {
				duplicate.add(curValue);
				continue;
			}
			result.append(curValue.getName());
			result.append("(");
			result.append(curValue.getId());
			result.append("),\n");
			added.put(curValue.getId(), curValue);
		}

		for (EnumValue curDuplicate : duplicate) {
			result.append(";\npublic static final ");
			result.append(pEnum.getName());
			result.append(" ");
			result.append(curDuplicate.getName());
			result.append(" = ");
			result.append(added.get(curDuplicate.getId()).getName());
		}

		result.append(";\npublic static ");
		result.append(pEnum.getName());
		result.append(" valueOf(int value) {\nswitch (value) {\n");
		for (EnumValue curValue : pEnum.getValues()) {
			if (duplicate.contains(curValue)) {
				continue;
			}
			result.append("case ");
			result.append(curValue.getId());
			result.append(": return ");
			result.append(curValue.getName());
			result.append(";\n");
		}
		result.append("default: return null;\n}\n}\nprivate ");
		result.append(pEnum.getName());
		result.append("(int value) {\nthis.value = value;\n}\nprivate int value;\npublic int getValue() {\nreturn value;\n}\n}\n\n");
		return result.toString();
	}

	private static void appendPackage(BufferedWriter w, String packageName) throws Exception {
		if (packageName != null) {
			w.append("package ");
			w.append(packageName);
			w.append(";\n\n");
		}
	}

	private static void appendImport(BufferedWriter w, String imp) throws Exception {
		w.append("import ");
		w.append(imp);
		w.append(";\n");
	}

	private static String constructType(ProtobufField curField, ProtobufMessage curMessage) {
		StringBuilder result = new StringBuilder();
		String javaType = curField.getFullyClarifiedJavaType();
		if (javaType == null) {
		}
		if (curField.getNature().equals("repeated") && !curField.getType().equals("bytes")) {
			result.append("java.util.List<");
		}
		result.append(javaType);
		if (curField.getNature().equals("repeated") && !curField.getType().equals("bytes")) {
			result.append(">");
		}
		return result.toString();
	}

	private static File createPackage(File parent, String packageName) {
		String[] paths = packageName.split("\\.");
		File curDirectory = parent;
		for (String curPath : paths) {
			File curDirPath = new File(curDirectory, curPath);
			if (!curDirPath.exists() || !curDirPath.isDirectory()) {
				curDirPath.mkdir();
			}
			curDirectory = curDirPath;
		}
		return curDirectory;
	}

	private static boolean hasRequired(ProtobufMessage message) {
		for (ProtobufField curField : message.getFields()) {
			if (curField.getNature().equals("required")) {
				return true;
			}
		}
		return false;
	}

}
